//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dbControlCobranzasModel", "FK_BancoCuenta", "Bancos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CapaModelo.Bancos), "Cuentas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapaModelo.Cuentas), true)]
[assembly: EdmRelationshipAttribute("dbControlCobranzasModel", "FK_ContratosDetallesContrato", "Contratos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CapaModelo.Contratos), "DetallesContratos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapaModelo.DetallesContratos), true)]
[assembly: EdmRelationshipAttribute("dbControlCobranzasModel", "FK_CuentaContratos", "Cuentas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CapaModelo.Cuentas), "Contratos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapaModelo.Contratos), true)]
[assembly: EdmRelationshipAttribute("dbControlCobranzasModel", "FK_InteresContratos", "Interes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CapaModelo.Interes), "Contratos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapaModelo.Contratos), true)]
[assembly: EdmRelationshipAttribute("dbControlCobranzasModel", "FK_usuarioContratos", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CapaModelo.usuarios), "Contratos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapaModelo.Contratos), true)]
[assembly: EdmRelationshipAttribute("dbControlCobranzasModel", "FK_usuarioCuenta", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CapaModelo.usuarios), "Cuentas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapaModelo.Cuentas), true)]
[assembly: EdmRelationshipAttribute("dbControlCobranzasModel", "FK_usuarios_rolUsuario1", "rolUsuario", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CapaModelo.rolUsuario), "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapaModelo.usuarios), true)]
[assembly: EdmRelationshipAttribute("dbControlCobranzasModel", "FK_Ubicacionusuario", "Ubicacions", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CapaModelo.Ubicacions), "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapaModelo.usuarios), true)]

#endregion

namespace CapaModelo
{
    #region Contexts
    
    /// <summary>
    /// No Metadataasdasd Documentation available.
    /// </summary>
    public partial class dbCobranzasEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbCobranzasEntities object using the connection string found in the 'dbCobranzasEntities' section of the application configuration file.
        /// </summary>
        public dbCobranzasEntities() : base("name=dbCobranzasEntities", "dbCobranzasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbCobranzasEntities object.
        /// </summary>
        public dbCobranzasEntities(string connectionString) : base(connectionString, "dbCobranzasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbCobranzasEntities object.
        /// </summary>
        public dbCobranzasEntities(EntityConnection connection) : base(connection, "dbCobranzasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bancos> Bancos
        {
            get
            {
                if ((_Bancos == null))
                {
                    _Bancos = base.CreateObjectSet<Bancos>("Bancos");
                }
                return _Bancos;
            }
        }
        private ObjectSet<Bancos> _Bancos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contratos> Contratos
        {
            get
            {
                if ((_Contratos == null))
                {
                    _Contratos = base.CreateObjectSet<Contratos>("Contratos");
                }
                return _Contratos;
            }
        }
        private ObjectSet<Contratos> _Contratos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cuentas> Cuentas
        {
            get
            {
                if ((_Cuentas == null))
                {
                    _Cuentas = base.CreateObjectSet<Cuentas>("Cuentas");
                }
                return _Cuentas;
            }
        }
        private ObjectSet<Cuentas> _Cuentas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DetallesContratos> DetallesContratos
        {
            get
            {
                if ((_DetallesContratos == null))
                {
                    _DetallesContratos = base.CreateObjectSet<DetallesContratos>("DetallesContratos");
                }
                return _DetallesContratos;
            }
        }
        private ObjectSet<DetallesContratos> _DetallesContratos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Interes> Interes
        {
            get
            {
                if ((_Interes == null))
                {
                    _Interes = base.CreateObjectSet<Interes>("Interes");
                }
                return _Interes;
            }
        }
        private ObjectSet<Interes> _Interes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rolUsuario> rolUsuario
        {
            get
            {
                if ((_rolUsuario == null))
                {
                    _rolUsuario = base.CreateObjectSet<rolUsuario>("rolUsuario");
                }
                return _rolUsuario;
            }
        }
        private ObjectSet<rolUsuario> _rolUsuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ubicacions> Ubicacions
        {
            get
            {
                if ((_Ubicacions == null))
                {
                    _Ubicacions = base.CreateObjectSet<Ubicacions>("Ubicacions");
                }
                return _Ubicacions;
            }
        }
        private ObjectSet<Ubicacions> _Ubicacions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bancos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBancos(Bancos bancos)
        {
            base.AddObject("Bancos", bancos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contratos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContratos(Contratos contratos)
        {
            base.AddObject("Contratos", contratos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cuentas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCuentas(Cuentas cuentas)
        {
            base.AddObject("Cuentas", cuentas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DetallesContratos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDetallesContratos(DetallesContratos detallesContratos)
        {
            base.AddObject("DetallesContratos", detallesContratos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Interes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInteres(Interes interes)
        {
            base.AddObject("Interes", interes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rolUsuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorolUsuario(rolUsuario rolUsuario)
        {
            base.AddObject("rolUsuario", rolUsuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ubicacions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUbicacions(Ubicacions ubicacions)
        {
            base.AddObject("Ubicacions", ubicacions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadataasdasdasd Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbControlCobranzasModel", Name="Bancos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bancos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bancos object.
        /// </summary>
        /// <param name="pkBancosID">Initial value of the pkBancosID property.</param>
        /// <param name="asNombreBanco">Initial value of the asNombreBanco property.</param>
        public static Bancos CreateBancos(global::System.Int32 pkBancosID, global::System.String asNombreBanco)
        {
            Bancos bancos = new Bancos();
            bancos.pkBancosID = pkBancosID;
            bancos.asNombreBanco = asNombreBanco;
            return bancos;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pkBancosID
        {
            get
            {
                return _pkBancosID;
            }
            set
            {
                if (_pkBancosID != value)
                {
                    OnpkBancosIDChanging(value);
                    ReportPropertyChanging("pkBancosID");
                    _pkBancosID = StructuralObject.SetValidValue(value, "pkBancosID");
                    ReportPropertyChanged("pkBancosID");
                    OnpkBancosIDChanged();
                }
            }
        }
        private global::System.Int32 _pkBancosID;
        partial void OnpkBancosIDChanging(global::System.Int32 value);
        partial void OnpkBancosIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asNombreBanco
        {
            get
            {
                return _asNombreBanco;
            }
            set
            {
                OnasNombreBancoChanging(value);
                ReportPropertyChanging("asNombreBanco");
                _asNombreBanco = StructuralObject.SetValidValue(value, false, "asNombreBanco");
                ReportPropertyChanged("asNombreBanco");
                OnasNombreBancoChanged();
            }
        }
        private global::System.String _asNombreBanco;
        partial void OnasNombreBancoChanging(global::System.String value);
        partial void OnasNombreBancoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_BancoCuenta", "Cuentas")]
        public EntityCollection<Cuentas> Cuentas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cuentas>("dbControlCobranzasModel.FK_BancoCuenta", "Cuentas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cuentas>("dbControlCobranzasModel.FK_BancoCuenta", "Cuentas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadataasdasdasd Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbControlCobranzasModel", Name="Contratos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contratos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contratos object.
        /// </summary>
        /// <param name="pkContratosID">Initial value of the pkContratosID property.</param>
        /// <param name="fkUsuariosID">Initial value of the fkUsuariosID property.</param>
        /// <param name="asNroContrato">Initial value of the asNroContrato property.</param>
        /// <param name="fkInteresID">Initial value of the fkInteresID property.</param>
        /// <param name="fkCuentaID">Initial value of the fkCuentaID property.</param>
        /// <param name="fechaContrato">Initial value of the FechaContrato property.</param>
        public static Contratos CreateContratos(global::System.Int32 pkContratosID, global::System.Int32 fkUsuariosID, global::System.String asNroContrato, global::System.Int32 fkInteresID, global::System.Int32 fkCuentaID, global::System.DateTime fechaContrato)
        {
            Contratos contratos = new Contratos();
            contratos.pkContratosID = pkContratosID;
            contratos.fkUsuariosID = fkUsuariosID;
            contratos.asNroContrato = asNroContrato;
            contratos.fkInteresID = fkInteresID;
            contratos.fkCuentaID = fkCuentaID;
            contratos.FechaContrato = fechaContrato;
            return contratos;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pkContratosID
        {
            get
            {
                return _pkContratosID;
            }
            set
            {
                if (_pkContratosID != value)
                {
                    OnpkContratosIDChanging(value);
                    ReportPropertyChanging("pkContratosID");
                    _pkContratosID = StructuralObject.SetValidValue(value, "pkContratosID");
                    ReportPropertyChanged("pkContratosID");
                    OnpkContratosIDChanged();
                }
            }
        }
        private global::System.Int32 _pkContratosID;
        partial void OnpkContratosIDChanging(global::System.Int32 value);
        partial void OnpkContratosIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fkUsuariosID
        {
            get
            {
                return _fkUsuariosID;
            }
            set
            {
                OnfkUsuariosIDChanging(value);
                ReportPropertyChanging("fkUsuariosID");
                _fkUsuariosID = StructuralObject.SetValidValue(value, "fkUsuariosID");
                ReportPropertyChanged("fkUsuariosID");
                OnfkUsuariosIDChanged();
            }
        }
        private global::System.Int32 _fkUsuariosID;
        partial void OnfkUsuariosIDChanging(global::System.Int32 value);
        partial void OnfkUsuariosIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asNroContrato
        {
            get
            {
                return _asNroContrato;
            }
            set
            {
                OnasNroContratoChanging(value);
                ReportPropertyChanging("asNroContrato");
                _asNroContrato = StructuralObject.SetValidValue(value, false, "asNroContrato");
                ReportPropertyChanged("asNroContrato");
                OnasNroContratoChanged();
            }
        }
        private global::System.String _asNroContrato;
        partial void OnasNroContratoChanging(global::System.String value);
        partial void OnasNroContratoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fkInteresID
        {
            get
            {
                return _fkInteresID;
            }
            set
            {
                OnfkInteresIDChanging(value);
                ReportPropertyChanging("fkInteresID");
                _fkInteresID = StructuralObject.SetValidValue(value, "fkInteresID");
                ReportPropertyChanged("fkInteresID");
                OnfkInteresIDChanged();
            }
        }
        private global::System.Int32 _fkInteresID;
        partial void OnfkInteresIDChanging(global::System.Int32 value);
        partial void OnfkInteresIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fkCuentaID
        {
            get
            {
                return _fkCuentaID;
            }
            set
            {
                OnfkCuentaIDChanging(value);
                ReportPropertyChanging("fkCuentaID");
                _fkCuentaID = StructuralObject.SetValidValue(value, "fkCuentaID");
                ReportPropertyChanged("fkCuentaID");
                OnfkCuentaIDChanged();
            }
        }
        private global::System.Int32 _fkCuentaID;
        partial void OnfkCuentaIDChanging(global::System.Int32 value);
        partial void OnfkCuentaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaContrato
        {
            get
            {
                return _FechaContrato;
            }
            set
            {
                OnFechaContratoChanging(value);
                ReportPropertyChanging("FechaContrato");
                _FechaContrato = StructuralObject.SetValidValue(value, "FechaContrato");
                ReportPropertyChanged("FechaContrato");
                OnFechaContratoChanged();
            }
        }
        private global::System.DateTime _FechaContrato;
        partial void OnFechaContratoChanging(global::System.DateTime value);
        partial void OnFechaContratoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_ContratosDetallesContrato", "DetallesContratos")]
        public EntityCollection<DetallesContratos> DetallesContratos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetallesContratos>("dbControlCobranzasModel.FK_ContratosDetallesContrato", "DetallesContratos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetallesContratos>("dbControlCobranzasModel.FK_ContratosDetallesContrato", "DetallesContratos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_CuentaContratos", "Cuentas")]
        public Cuentas Cuentas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cuentas>("dbControlCobranzasModel.FK_CuentaContratos", "Cuentas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cuentas>("dbControlCobranzasModel.FK_CuentaContratos", "Cuentas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cuentas> CuentasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cuentas>("dbControlCobranzasModel.FK_CuentaContratos", "Cuentas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cuentas>("dbControlCobranzasModel.FK_CuentaContratos", "Cuentas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_InteresContratos", "Interes")]
        public Interes Interes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Interes>("dbControlCobranzasModel.FK_InteresContratos", "Interes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Interes>("dbControlCobranzasModel.FK_InteresContratos", "Interes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Interes> InteresReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Interes>("dbControlCobranzasModel.FK_InteresContratos", "Interes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Interes>("dbControlCobranzasModel.FK_InteresContratos", "Interes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_usuarioContratos", "usuarios")]
        public usuarios usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("dbControlCobranzasModel.FK_usuarioContratos", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("dbControlCobranzasModel.FK_usuarioContratos", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("dbControlCobranzasModel.FK_usuarioContratos", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("dbControlCobranzasModel.FK_usuarioContratos", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata asdasdasdDocumentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbControlCobranzasModel", Name="Cuentas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cuentas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cuentas object.
        /// </summary>
        /// <param name="pkCuentaID">Initial value of the pkCuentaID property.</param>
        /// <param name="asNroCuenta">Initial value of the asNroCuenta property.</param>
        /// <param name="fkUsuarioID">Initial value of the fkUsuarioID property.</param>
        /// <param name="fkBancoID">Initial value of the fkBancoID property.</param>
        public static Cuentas CreateCuentas(global::System.Int32 pkCuentaID, global::System.String asNroCuenta, global::System.Int32 fkUsuarioID, global::System.Int32 fkBancoID)
        {
            Cuentas cuentas = new Cuentas();
            cuentas.pkCuentaID = pkCuentaID;
            cuentas.asNroCuenta = asNroCuenta;
            cuentas.fkUsuarioID = fkUsuarioID;
            cuentas.fkBancoID = fkBancoID;
            return cuentas;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pkCuentaID
        {
            get
            {
                return _pkCuentaID;
            }
            set
            {
                if (_pkCuentaID != value)
                {
                    OnpkCuentaIDChanging(value);
                    ReportPropertyChanging("pkCuentaID");
                    _pkCuentaID = StructuralObject.SetValidValue(value, "pkCuentaID");
                    ReportPropertyChanged("pkCuentaID");
                    OnpkCuentaIDChanged();
                }
            }
        }
        private global::System.Int32 _pkCuentaID;
        partial void OnpkCuentaIDChanging(global::System.Int32 value);
        partial void OnpkCuentaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asNroCuenta
        {
            get
            {
                return _asNroCuenta;
            }
            set
            {
                OnasNroCuentaChanging(value);
                ReportPropertyChanging("asNroCuenta");
                _asNroCuenta = StructuralObject.SetValidValue(value, false, "asNroCuenta");
                ReportPropertyChanged("asNroCuenta");
                OnasNroCuentaChanged();
            }
        }
        private global::System.String _asNroCuenta;
        partial void OnasNroCuentaChanging(global::System.String value);
        partial void OnasNroCuentaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fkUsuarioID
        {
            get
            {
                return _fkUsuarioID;
            }
            set
            {
                OnfkUsuarioIDChanging(value);
                ReportPropertyChanging("fkUsuarioID");
                _fkUsuarioID = StructuralObject.SetValidValue(value, "fkUsuarioID");
                ReportPropertyChanged("fkUsuarioID");
                OnfkUsuarioIDChanged();
            }
        }
        private global::System.Int32 _fkUsuarioID;
        partial void OnfkUsuarioIDChanging(global::System.Int32 value);
        partial void OnfkUsuarioIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fkBancoID
        {
            get
            {
                return _fkBancoID;
            }
            set
            {
                OnfkBancoIDChanging(value);
                ReportPropertyChanging("fkBancoID");
                _fkBancoID = StructuralObject.SetValidValue(value, "fkBancoID");
                ReportPropertyChanged("fkBancoID");
                OnfkBancoIDChanged();
            }
        }
        private global::System.Int32 _fkBancoID;
        partial void OnfkBancoIDChanging(global::System.Int32 value);
        partial void OnfkBancoIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_BancoCuenta", "Bancos")]
        public Bancos Bancos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bancos>("dbControlCobranzasModel.FK_BancoCuenta", "Bancos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bancos>("dbControlCobranzasModel.FK_BancoCuenta", "Bancos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bancos> BancosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bancos>("dbControlCobranzasModel.FK_BancoCuenta", "Bancos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bancos>("dbControlCobranzasModel.FK_BancoCuenta", "Bancos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_CuentaContratos", "Contratos")]
        public EntityCollection<Contratos> Contratos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Contratos>("dbControlCobranzasModel.FK_CuentaContratos", "Contratos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Contratos>("dbControlCobranzasModel.FK_CuentaContratos", "Contratos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_usuarioCuenta", "usuarios")]
        public usuarios usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("dbControlCobranzasModel.FK_usuarioCuenta", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("dbControlCobranzasModel.FK_usuarioCuenta", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("dbControlCobranzasModel.FK_usuarioCuenta", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("dbControlCobranzasModel.FK_usuarioCuenta", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata asdasdasdDocumentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbControlCobranzasModel", Name="DetallesContratos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DetallesContratos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DetallesContratos object.
        /// </summary>
        /// <param name="pkDetallesID">Initial value of the pkDetallesID property.</param>
        /// <param name="fkContratosID">Initial value of the fkContratosID property.</param>
        /// <param name="monto">Initial value of the Monto property.</param>
        /// <param name="interes">Initial value of the Interes property.</param>
        /// <param name="fechaLiquidacion">Initial value of the FechaLiquidacion property.</param>
        /// <param name="fechaVencimiento">Initial value of the FechaVencimiento property.</param>
        /// <param name="asDias">Initial value of the asDias property.</param>
        /// <param name="asMontoVencido">Initial value of the asMontoVencido property.</param>
        /// <param name="asMontoCobrado">Initial value of the asMontoCobrado property.</param>
        /// <param name="asAbonoCapital">Initial value of the asAbonoCapital property.</param>
        /// <param name="fechaCobro">Initial value of the FechaCobro property.</param>
        /// <param name="asSaldoPendiente">Initial value of the asSaldoPendiente property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        /// <param name="fechaActualizacion">Initial value of the FechaActualizacion property.</param>
        public static DetallesContratos CreateDetallesContratos(global::System.Int32 pkDetallesID, global::System.Int32 fkContratosID, global::System.String monto, global::System.String interes, global::System.Int32 fechaLiquidacion, global::System.DateTime fechaVencimiento, global::System.String asDias, global::System.String asMontoVencido, global::System.String asMontoCobrado, global::System.String asAbonoCapital, global::System.DateTime fechaCobro, global::System.String asSaldoPendiente, global::System.DateTime fechaCreacion, global::System.DateTime fechaActualizacion)
        {
            DetallesContratos detallesContratos = new DetallesContratos();
            detallesContratos.pkDetallesID = pkDetallesID;
            detallesContratos.fkContratosID = fkContratosID;
            detallesContratos.Monto = monto;
            detallesContratos.Interes = interes;
            detallesContratos.FechaLiquidacion = fechaLiquidacion;
            detallesContratos.FechaVencimiento = fechaVencimiento;
            detallesContratos.asDias = asDias;
            detallesContratos.asMontoVencido = asMontoVencido;
            detallesContratos.asMontoCobrado = asMontoCobrado;
            detallesContratos.asAbonoCapital = asAbonoCapital;
            detallesContratos.FechaCobro = fechaCobro;
            detallesContratos.asSaldoPendiente = asSaldoPendiente;
            detallesContratos.FechaCreacion = fechaCreacion;
            detallesContratos.FechaActualizacion = fechaActualizacion;
            return detallesContratos;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pkDetallesID
        {
            get
            {
                return _pkDetallesID;
            }
            set
            {
                if (_pkDetallesID != value)
                {
                    OnpkDetallesIDChanging(value);
                    ReportPropertyChanging("pkDetallesID");
                    _pkDetallesID = StructuralObject.SetValidValue(value, "pkDetallesID");
                    ReportPropertyChanged("pkDetallesID");
                    OnpkDetallesIDChanged();
                }
            }
        }
        private global::System.Int32 _pkDetallesID;
        partial void OnpkDetallesIDChanging(global::System.Int32 value);
        partial void OnpkDetallesIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fkContratosID
        {
            get
            {
                return _fkContratosID;
            }
            set
            {
                OnfkContratosIDChanging(value);
                ReportPropertyChanging("fkContratosID");
                _fkContratosID = StructuralObject.SetValidValue(value, "fkContratosID");
                ReportPropertyChanged("fkContratosID");
                OnfkContratosIDChanged();
            }
        }
        private global::System.Int32 _fkContratosID;
        partial void OnfkContratosIDChanging(global::System.Int32 value);
        partial void OnfkContratosIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = StructuralObject.SetValidValue(value, false, "Monto");
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private global::System.String _Monto;
        partial void OnMontoChanging(global::System.String value);
        partial void OnMontoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Interes
        {
            get
            {
                return _Interes;
            }
            set
            {
                OnInteresChanging(value);
                ReportPropertyChanging("Interes");
                _Interes = StructuralObject.SetValidValue(value, false, "Interes");
                ReportPropertyChanged("Interes");
                OnInteresChanged();
            }
        }
        private global::System.String _Interes;
        partial void OnInteresChanging(global::System.String value);
        partial void OnInteresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FechaLiquidacion
        {
            get
            {
                return _FechaLiquidacion;
            }
            set
            {
                OnFechaLiquidacionChanging(value);
                ReportPropertyChanging("FechaLiquidacion");
                _FechaLiquidacion = StructuralObject.SetValidValue(value, "FechaLiquidacion");
                ReportPropertyChanged("FechaLiquidacion");
                OnFechaLiquidacionChanged();
            }
        }
        private global::System.Int32 _FechaLiquidacion;
        partial void OnFechaLiquidacionChanging(global::System.Int32 value);
        partial void OnFechaLiquidacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaVencimiento
        {
            get
            {
                return _FechaVencimiento;
            }
            set
            {
                OnFechaVencimientoChanging(value);
                ReportPropertyChanging("FechaVencimiento");
                _FechaVencimiento = StructuralObject.SetValidValue(value, "FechaVencimiento");
                ReportPropertyChanged("FechaVencimiento");
                OnFechaVencimientoChanged();
            }
        }
        private global::System.DateTime _FechaVencimiento;
        partial void OnFechaVencimientoChanging(global::System.DateTime value);
        partial void OnFechaVencimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asDias
        {
            get
            {
                return _asDias;
            }
            set
            {
                OnasDiasChanging(value);
                ReportPropertyChanging("asDias");
                _asDias = StructuralObject.SetValidValue(value, false, "asDias");
                ReportPropertyChanged("asDias");
                OnasDiasChanged();
            }
        }
        private global::System.String _asDias;
        partial void OnasDiasChanging(global::System.String value);
        partial void OnasDiasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asMontoVencido
        {
            get
            {
                return _asMontoVencido;
            }
            set
            {
                OnasMontoVencidoChanging(value);
                ReportPropertyChanging("asMontoVencido");
                _asMontoVencido = StructuralObject.SetValidValue(value, false, "asMontoVencido");
                ReportPropertyChanged("asMontoVencido");
                OnasMontoVencidoChanged();
            }
        }
        private global::System.String _asMontoVencido;
        partial void OnasMontoVencidoChanging(global::System.String value);
        partial void OnasMontoVencidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asMontoCobrado
        {
            get
            {
                return _asMontoCobrado;
            }
            set
            {
                OnasMontoCobradoChanging(value);
                ReportPropertyChanging("asMontoCobrado");
                _asMontoCobrado = StructuralObject.SetValidValue(value, false, "asMontoCobrado");
                ReportPropertyChanged("asMontoCobrado");
                OnasMontoCobradoChanged();
            }
        }
        private global::System.String _asMontoCobrado;
        partial void OnasMontoCobradoChanging(global::System.String value);
        partial void OnasMontoCobradoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asAbonoCapital
        {
            get
            {
                return _asAbonoCapital;
            }
            set
            {
                OnasAbonoCapitalChanging(value);
                ReportPropertyChanging("asAbonoCapital");
                _asAbonoCapital = StructuralObject.SetValidValue(value, false, "asAbonoCapital");
                ReportPropertyChanged("asAbonoCapital");
                OnasAbonoCapitalChanged();
            }
        }
        private global::System.String _asAbonoCapital;
        partial void OnasAbonoCapitalChanging(global::System.String value);
        partial void OnasAbonoCapitalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCobro
        {
            get
            {
                return _FechaCobro;
            }
            set
            {
                OnFechaCobroChanging(value);
                ReportPropertyChanging("FechaCobro");
                _FechaCobro = StructuralObject.SetValidValue(value, "FechaCobro");
                ReportPropertyChanged("FechaCobro");
                OnFechaCobroChanged();
            }
        }
        private global::System.DateTime _FechaCobro;
        partial void OnFechaCobroChanging(global::System.DateTime value);
        partial void OnFechaCobroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asSaldoPendiente
        {
            get
            {
                return _asSaldoPendiente;
            }
            set
            {
                OnasSaldoPendienteChanging(value);
                ReportPropertyChanging("asSaldoPendiente");
                _asSaldoPendiente = StructuralObject.SetValidValue(value, false, "asSaldoPendiente");
                ReportPropertyChanged("asSaldoPendiente");
                OnasSaldoPendienteChanged();
            }
        }
        private global::System.String _asSaldoPendiente;
        partial void OnasSaldoPendienteChanging(global::System.String value);
        partial void OnasSaldoPendienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value, "FechaCreacion");
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaActualizacion
        {
            get
            {
                return _FechaActualizacion;
            }
            set
            {
                OnFechaActualizacionChanging(value);
                ReportPropertyChanging("FechaActualizacion");
                _FechaActualizacion = StructuralObject.SetValidValue(value, "FechaActualizacion");
                ReportPropertyChanged("FechaActualizacion");
                OnFechaActualizacionChanged();
            }
        }
        private global::System.DateTime _FechaActualizacion;
        partial void OnFechaActualizacionChanging(global::System.DateTime value);
        partial void OnFechaActualizacionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_ContratosDetallesContrato", "Contratos")]
        public Contratos Contratos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contratos>("dbControlCobranzasModel.FK_ContratosDetallesContrato", "Contratos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contratos>("dbControlCobranzasModel.FK_ContratosDetallesContrato", "Contratos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contratos> ContratosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contratos>("dbControlCobranzasModel.FK_ContratosDetallesContrato", "Contratos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contratos>("dbControlCobranzasModel.FK_ContratosDetallesContrato", "Contratos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadataasdasdasd Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbControlCobranzasModel", Name="Interes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Interes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Interes object.
        /// </summary>
        /// <param name="pkInteresID">Initial value of the pkInteresID property.</param>
        /// <param name="asPorcentaje">Initial value of the asPorcentaje property.</param>
        public static Interes CreateInteres(global::System.Int32 pkInteresID, global::System.String asPorcentaje)
        {
            Interes interes = new Interes();
            interes.pkInteresID = pkInteresID;
            interes.asPorcentaje = asPorcentaje;
            return interes;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pkInteresID
        {
            get
            {
                return _pkInteresID;
            }
            set
            {
                if (_pkInteresID != value)
                {
                    OnpkInteresIDChanging(value);
                    ReportPropertyChanging("pkInteresID");
                    _pkInteresID = StructuralObject.SetValidValue(value, "pkInteresID");
                    ReportPropertyChanged("pkInteresID");
                    OnpkInteresIDChanged();
                }
            }
        }
        private global::System.Int32 _pkInteresID;
        partial void OnpkInteresIDChanging(global::System.Int32 value);
        partial void OnpkInteresIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asPorcentaje
        {
            get
            {
                return _asPorcentaje;
            }
            set
            {
                OnasPorcentajeChanging(value);
                ReportPropertyChanging("asPorcentaje");
                _asPorcentaje = StructuralObject.SetValidValue(value, false, "asPorcentaje");
                ReportPropertyChanged("asPorcentaje");
                OnasPorcentajeChanged();
            }
        }
        private global::System.String _asPorcentaje;
        partial void OnasPorcentajeChanging(global::System.String value);
        partial void OnasPorcentajeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_InteresContratos", "Contratos")]
        public EntityCollection<Contratos> Contratos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Contratos>("dbControlCobranzasModel.FK_InteresContratos", "Contratos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Contratos>("dbControlCobranzasModel.FK_InteresContratos", "Contratos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadataasdasdasd Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbControlCobranzasModel", Name="rolUsuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rolUsuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rolUsuario object.
        /// </summary>
        /// <param name="pkRolUsuarioID">Initial value of the pkRolUsuarioID property.</param>
        public static rolUsuario CreaterolUsuario(global::System.Int32 pkRolUsuarioID)
        {
            rolUsuario rolUsuario = new rolUsuario();
            rolUsuario.pkRolUsuarioID = pkRolUsuarioID;
            return rolUsuario;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pkRolUsuarioID
        {
            get
            {
                return _pkRolUsuarioID;
            }
            set
            {
                if (_pkRolUsuarioID != value)
                {
                    OnpkRolUsuarioIDChanging(value);
                    ReportPropertyChanging("pkRolUsuarioID");
                    _pkRolUsuarioID = StructuralObject.SetValidValue(value, "pkRolUsuarioID");
                    ReportPropertyChanged("pkRolUsuarioID");
                    OnpkRolUsuarioIDChanged();
                }
            }
        }
        private global::System.Int32 _pkRolUsuarioID;
        partial void OnpkRolUsuarioIDChanging(global::System.Int32 value);
        partial void OnpkRolUsuarioIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String asDescripcion
        {
            get
            {
                return _asDescripcion;
            }
            set
            {
                OnasDescripcionChanging(value);
                ReportPropertyChanging("asDescripcion");
                _asDescripcion = StructuralObject.SetValidValue(value, true, "asDescripcion");
                ReportPropertyChanged("asDescripcion");
                OnasDescripcionChanged();
            }
        }
        private global::System.String _asDescripcion;
        partial void OnasDescripcionChanging(global::System.String value);
        partial void OnasDescripcionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_usuarios_rolUsuario1", "usuarios")]
        public EntityCollection<usuarios> usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuarios>("dbControlCobranzasModel.FK_usuarios_rolUsuario1", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuarios>("dbControlCobranzasModel.FK_usuarios_rolUsuario1", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadataasdasdasd Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbControlCobranzasModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadataasdasda Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbControlCobranzasModel", Name="Ubicacions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ubicacions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ubicacions object.
        /// </summary>
        /// <param name="pkUbicacionID">Initial value of the pkUbicacionID property.</param>
        /// <param name="asCiudades">Initial value of the asCiudades property.</param>
        public static Ubicacions CreateUbicacions(global::System.Int32 pkUbicacionID, global::System.String asCiudades)
        {
            Ubicacions ubicacions = new Ubicacions();
            ubicacions.pkUbicacionID = pkUbicacionID;
            ubicacions.asCiudades = asCiudades;
            return ubicacions;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pkUbicacionID
        {
            get
            {
                return _pkUbicacionID;
            }
            set
            {
                if (_pkUbicacionID != value)
                {
                    OnpkUbicacionIDChanging(value);
                    ReportPropertyChanging("pkUbicacionID");
                    _pkUbicacionID = StructuralObject.SetValidValue(value, "pkUbicacionID");
                    ReportPropertyChanged("pkUbicacionID");
                    OnpkUbicacionIDChanged();
                }
            }
        }
        private global::System.Int32 _pkUbicacionID;
        partial void OnpkUbicacionIDChanging(global::System.Int32 value);
        partial void OnpkUbicacionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asCiudades
        {
            get
            {
                return _asCiudades;
            }
            set
            {
                OnasCiudadesChanging(value);
                ReportPropertyChanging("asCiudades");
                _asCiudades = StructuralObject.SetValidValue(value, false, "asCiudades");
                ReportPropertyChanged("asCiudades");
                OnasCiudadesChanged();
            }
        }
        private global::System.String _asCiudades;
        partial void OnasCiudadesChanging(global::System.String value);
        partial void OnasCiudadesChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_Ubicacionusuario", "usuarios")]
        public EntityCollection<usuarios> usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuarios>("dbControlCobranzasModel.FK_Ubicacionusuario", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuarios>("dbControlCobranzasModel.FK_Ubicacionusuario", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadataasdasdasdads Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbControlCobranzasModel", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuarios object.
        /// </summary>
        /// <param name="pkUsuariosID">Initial value of the pkUsuariosID property.</param>
        /// <param name="asCedula">Initial value of the asCedula property.</param>
        /// <param name="asNombre">Initial value of the asNombre property.</param>
        /// <param name="asApellido">Initial value of the asApellido property.</param>
        /// <param name="fkUbicacionID">Initial value of the fkUbicacionID property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        public static usuarios Createusuarios(global::System.Int32 pkUsuariosID, global::System.String asCedula, global::System.String asNombre, global::System.String asApellido, global::System.Int32 fkUbicacionID, global::System.DateTime fechaCreacion)
        {
            usuarios usuarios = new usuarios();
            usuarios.pkUsuariosID = pkUsuariosID;
            usuarios.asCedula = asCedula;
            usuarios.asNombre = asNombre;
            usuarios.asApellido = asApellido;
            usuarios.fkUbicacionID = fkUbicacionID;
            usuarios.FechaCreacion = fechaCreacion;
            return usuarios;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pkUsuariosID
        {
            get
            {
                return _pkUsuariosID;
            }
            set
            {
                if (_pkUsuariosID != value)
                {
                    OnpkUsuariosIDChanging(value);
                    ReportPropertyChanging("pkUsuariosID");
                    _pkUsuariosID = StructuralObject.SetValidValue(value, "pkUsuariosID");
                    ReportPropertyChanged("pkUsuariosID");
                    OnpkUsuariosIDChanged();
                }
            }
        }
        private global::System.Int32 _pkUsuariosID;
        partial void OnpkUsuariosIDChanging(global::System.Int32 value);
        partial void OnpkUsuariosIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asCedula
        {
            get
            {
                return _asCedula;
            }
            set
            {
                OnasCedulaChanging(value);
                ReportPropertyChanging("asCedula");
                _asCedula = StructuralObject.SetValidValue(value, false, "asCedula");
                ReportPropertyChanged("asCedula");
                OnasCedulaChanged();
            }
        }
        private global::System.String _asCedula;
        partial void OnasCedulaChanging(global::System.String value);
        partial void OnasCedulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asNombre
        {
            get
            {
                return _asNombre;
            }
            set
            {
                OnasNombreChanging(value);
                ReportPropertyChanging("asNombre");
                _asNombre = StructuralObject.SetValidValue(value, false, "asNombre");
                ReportPropertyChanged("asNombre");
                OnasNombreChanged();
            }
        }
        private global::System.String _asNombre;
        partial void OnasNombreChanging(global::System.String value);
        partial void OnasNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asApellido
        {
            get
            {
                return _asApellido;
            }
            set
            {
                OnasApellidoChanging(value);
                ReportPropertyChanging("asApellido");
                _asApellido = StructuralObject.SetValidValue(value, false, "asApellido");
                ReportPropertyChanged("asApellido");
                OnasApellidoChanged();
            }
        }
        private global::System.String _asApellido;
        partial void OnasApellidoChanging(global::System.String value);
        partial void OnasApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String asUsername
        {
            get
            {
                return _asUsername;
            }
            set
            {
                OnasUsernameChanging(value);
                ReportPropertyChanging("asUsername");
                _asUsername = StructuralObject.SetValidValue(value, true, "asUsername");
                ReportPropertyChanged("asUsername");
                OnasUsernameChanged();
            }
        }
        private global::System.String _asUsername;
        partial void OnasUsernameChanging(global::System.String value);
        partial void OnasUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String asPassword
        {
            get
            {
                return _asPassword;
            }
            set
            {
                OnasPasswordChanging(value);
                ReportPropertyChanging("asPassword");
                _asPassword = StructuralObject.SetValidValue(value, true, "asPassword");
                ReportPropertyChanged("asPassword");
                OnasPasswordChanged();
            }
        }
        private global::System.String _asPassword;
        partial void OnasPasswordChanging(global::System.String value);
        partial void OnasPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fkRolUsuarioID
        {
            get
            {
                return _fkRolUsuarioID;
            }
            set
            {
                OnfkRolUsuarioIDChanging(value);
                ReportPropertyChanging("fkRolUsuarioID");
                _fkRolUsuarioID = StructuralObject.SetValidValue(value, "fkRolUsuarioID");
                ReportPropertyChanged("fkRolUsuarioID");
                OnfkRolUsuarioIDChanged();
            }
        }
        private Nullable<global::System.Int32> _fkRolUsuarioID;
        partial void OnfkRolUsuarioIDChanging(Nullable<global::System.Int32> value);
        partial void OnfkRolUsuarioIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fkUbicacionID
        {
            get
            {
                return _fkUbicacionID;
            }
            set
            {
                OnfkUbicacionIDChanging(value);
                ReportPropertyChanging("fkUbicacionID");
                _fkUbicacionID = StructuralObject.SetValidValue(value, "fkUbicacionID");
                ReportPropertyChanged("fkUbicacionID");
                OnfkUbicacionIDChanged();
            }
        }
        private global::System.Int32 _fkUbicacionID;
        partial void OnfkUbicacionIDChanging(global::System.Int32 value);
        partial void OnfkUbicacionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value, "FechaCreacion");
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_usuarioContratos", "Contratos")]
        public EntityCollection<Contratos> Contratos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Contratos>("dbControlCobranzasModel.FK_usuarioContratos", "Contratos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Contratos>("dbControlCobranzasModel.FK_usuarioContratos", "Contratos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_usuarioCuenta", "Cuentas")]
        public EntityCollection<Cuentas> Cuentas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cuentas>("dbControlCobranzasModel.FK_usuarioCuenta", "Cuentas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cuentas>("dbControlCobranzasModel.FK_usuarioCuenta", "Cuentas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_usuarios_rolUsuario1", "rolUsuario")]
        public rolUsuario rolUsuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<rolUsuario>("dbControlCobranzasModel.FK_usuarios_rolUsuario1", "rolUsuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<rolUsuario>("dbControlCobranzasModel.FK_usuarios_rolUsuario1", "rolUsuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<rolUsuario> rolUsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<rolUsuario>("dbControlCobranzasModel.FK_usuarios_rolUsuario1", "rolUsuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<rolUsuario>("dbControlCobranzasModel.FK_usuarios_rolUsuario1", "rolUsuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_Ubicacionusuario", "Ubicacions")]
        public Ubicacions Ubicacions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ubicacions>("dbControlCobranzasModel.FK_Ubicacionusuario", "Ubicacions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ubicacions>("dbControlCobranzasModel.FK_Ubicacionusuario", "Ubicacions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ubicacions> UbicacionsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ubicacions>("dbControlCobranzasModel.FK_Ubicacionusuario", "Ubicacions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ubicacions>("dbControlCobranzasModel.FK_Ubicacionusuario", "Ubicacions", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
