//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dbControlCobranzasModel", "FK_usuarios_personas", "personas", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CapaModelo.persona), "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapaModelo.usuario), true)]
[assembly: EdmRelationshipAttribute("dbControlCobranzasModel", "FK_usuarios_rolUsuario", "rolUsuario", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CapaModelo.rolUsuario), "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CapaModelo.usuario), true)]

#endregion

namespace CapaModelo
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbControlCobranzasEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbControlCobranzasEntities object using the connection string found in the 'dbControlCobranzasEntities' section of the application configuration file.
        /// </summary>
        public dbControlCobranzasEntities() : base("name=dbControlCobranzasEntities", "dbControlCobranzasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbControlCobranzasEntities object.
        /// </summary>
        public dbControlCobranzasEntities(string connectionString) : base(connectionString, "dbControlCobranzasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbControlCobranzasEntities object.
        /// </summary>
        public dbControlCobranzasEntities(EntityConnection connection) : base(connection, "dbControlCobranzasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<persona> personas
        {
            get
            {
                if ((_personas == null))
                {
                    _personas = base.CreateObjectSet<persona>("personas");
                }
                return _personas;
            }
        }
        private ObjectSet<persona> _personas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rolUsuario> rolUsuarios
        {
            get
            {
                if ((_rolUsuarios == null))
                {
                    _rolUsuarios = base.CreateObjectSet<rolUsuario>("rolUsuarios");
                }
                return _rolUsuarios;
            }
        }
        private ObjectSet<rolUsuario> _rolUsuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuario> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuario>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuario> _usuarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the personas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopersonas(persona persona)
        {
            base.AddObject("personas", persona);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rolUsuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorolUsuarios(rolUsuario rolUsuario)
        {
            base.AddObject("rolUsuarios", rolUsuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuarios(usuario usuario)
        {
            base.AddObject("usuarios", usuario);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbControlCobranzasModel", Name="persona")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class persona : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new persona object.
        /// </summary>
        /// <param name="pkPersonaID">Initial value of the pkPersonaID property.</param>
        public static persona Createpersona(global::System.Int32 pkPersonaID)
        {
            persona persona = new persona();
            persona.pkPersonaID = pkPersonaID;
            return persona;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pkPersonaID
        {
            get
            {
                return _pkPersonaID;
            }
            set
            {
                if (_pkPersonaID != value)
                {
                    OnpkPersonaIDChanging(value);
                    ReportPropertyChanging("pkPersonaID");
                    _pkPersonaID = StructuralObject.SetValidValue(value, "pkPersonaID");
                    ReportPropertyChanged("pkPersonaID");
                    OnpkPersonaIDChanged();
                }
            }
        }
        private global::System.Int32 _pkPersonaID;
        partial void OnpkPersonaIDChanging(global::System.Int32 value);
        partial void OnpkPersonaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String asNombre
        {
            get
            {
                return _asNombre;
            }
            set
            {
                OnasNombreChanging(value);
                ReportPropertyChanging("asNombre");
                _asNombre = StructuralObject.SetValidValue(value, true, "asNombre");
                ReportPropertyChanged("asNombre");
                OnasNombreChanged();
            }
        }
        private global::System.String _asNombre;
        partial void OnasNombreChanging(global::System.String value);
        partial void OnasNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String asApellido
        {
            get
            {
                return _asApellido;
            }
            set
            {
                OnasApellidoChanging(value);
                ReportPropertyChanging("asApellido");
                _asApellido = StructuralObject.SetValidValue(value, true, "asApellido");
                ReportPropertyChanged("asApellido");
                OnasApellidoChanged();
            }
        }
        private global::System.String _asApellido;
        partial void OnasApellidoChanging(global::System.String value);
        partial void OnasApellidoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_usuarios_personas", "usuarios")]
        public EntityCollection<usuario> usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuario>("dbControlCobranzasModel.FK_usuarios_personas", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuario>("dbControlCobranzasModel.FK_usuarios_personas", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbControlCobranzasModel", Name="rolUsuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rolUsuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rolUsuario object.
        /// </summary>
        /// <param name="pkRolUsuarioID">Initial value of the pkRolUsuarioID property.</param>
        public static rolUsuario CreaterolUsuario(global::System.Int32 pkRolUsuarioID)
        {
            rolUsuario rolUsuario = new rolUsuario();
            rolUsuario.pkRolUsuarioID = pkRolUsuarioID;
            return rolUsuario;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pkRolUsuarioID
        {
            get
            {
                return _pkRolUsuarioID;
            }
            set
            {
                if (_pkRolUsuarioID != value)
                {
                    OnpkRolUsuarioIDChanging(value);
                    ReportPropertyChanging("pkRolUsuarioID");
                    _pkRolUsuarioID = StructuralObject.SetValidValue(value, "pkRolUsuarioID");
                    ReportPropertyChanged("pkRolUsuarioID");
                    OnpkRolUsuarioIDChanged();
                }
            }
        }
        private global::System.Int32 _pkRolUsuarioID;
        partial void OnpkRolUsuarioIDChanging(global::System.Int32 value);
        partial void OnpkRolUsuarioIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String asDescripcion
        {
            get
            {
                return _asDescripcion;
            }
            set
            {
                OnasDescripcionChanging(value);
                ReportPropertyChanging("asDescripcion");
                _asDescripcion = StructuralObject.SetValidValue(value, true, "asDescripcion");
                ReportPropertyChanged("asDescripcion");
                OnasDescripcionChanged();
            }
        }
        private global::System.String _asDescripcion;
        partial void OnasDescripcionChanging(global::System.String value);
        partial void OnasDescripcionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_usuarios_rolUsuario", "usuarios")]
        public EntityCollection<usuario> usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuario>("dbControlCobranzasModel.FK_usuarios_rolUsuario", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuario>("dbControlCobranzasModel.FK_usuarios_rolUsuario", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbControlCobranzasModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbControlCobranzasModel", Name="usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuario object.
        /// </summary>
        /// <param name="pkUsuariosID">Initial value of the pkUsuariosID property.</param>
        public static usuario Createusuario(global::System.Int32 pkUsuariosID)
        {
            usuario usuario = new usuario();
            usuario.pkUsuariosID = pkUsuariosID;
            return usuario;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pkUsuariosID
        {
            get
            {
                return _pkUsuariosID;
            }
            set
            {
                if (_pkUsuariosID != value)
                {
                    OnpkUsuariosIDChanging(value);
                    ReportPropertyChanging("pkUsuariosID");
                    _pkUsuariosID = StructuralObject.SetValidValue(value, "pkUsuariosID");
                    ReportPropertyChanged("pkUsuariosID");
                    OnpkUsuariosIDChanged();
                }
            }
        }
        private global::System.Int32 _pkUsuariosID;
        partial void OnpkUsuariosIDChanging(global::System.Int32 value);
        partial void OnpkUsuariosIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String asUsername
        {
            get
            {
                return _asUsername;
            }
            set
            {
                OnasUsernameChanging(value);
                ReportPropertyChanging("asUsername");
                _asUsername = StructuralObject.SetValidValue(value, true, "asUsername");
                ReportPropertyChanged("asUsername");
                OnasUsernameChanged();
            }
        }
        private global::System.String _asUsername;
        partial void OnasUsernameChanging(global::System.String value);
        partial void OnasUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String asPassword
        {
            get
            {
                return _asPassword;
            }
            set
            {
                OnasPasswordChanging(value);
                ReportPropertyChanging("asPassword");
                _asPassword = StructuralObject.SetValidValue(value, true, "asPassword");
                ReportPropertyChanged("asPassword");
                OnasPasswordChanged();
            }
        }
        private global::System.String _asPassword;
        partial void OnasPasswordChanging(global::System.String value);
        partial void OnasPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fkPersonaID
        {
            get
            {
                return _fkPersonaID;
            }
            set
            {
                OnfkPersonaIDChanging(value);
                ReportPropertyChanging("fkPersonaID");
                _fkPersonaID = StructuralObject.SetValidValue(value, "fkPersonaID");
                ReportPropertyChanged("fkPersonaID");
                OnfkPersonaIDChanged();
            }
        }
        private Nullable<global::System.Int32> _fkPersonaID;
        partial void OnfkPersonaIDChanging(Nullable<global::System.Int32> value);
        partial void OnfkPersonaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fkRolUsuarioID
        {
            get
            {
                return _fkRolUsuarioID;
            }
            set
            {
                OnfkRolUsuarioIDChanging(value);
                ReportPropertyChanging("fkRolUsuarioID");
                _fkRolUsuarioID = StructuralObject.SetValidValue(value, "fkRolUsuarioID");
                ReportPropertyChanged("fkRolUsuarioID");
                OnfkRolUsuarioIDChanged();
            }
        }
        private Nullable<global::System.Int32> _fkRolUsuarioID;
        partial void OnfkRolUsuarioIDChanging(Nullable<global::System.Int32> value);
        partial void OnfkRolUsuarioIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_usuarios_personas", "personas")]
        public persona persona
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<persona>("dbControlCobranzasModel.FK_usuarios_personas", "personas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<persona>("dbControlCobranzasModel.FK_usuarios_personas", "personas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<persona> personaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<persona>("dbControlCobranzasModel.FK_usuarios_personas", "personas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<persona>("dbControlCobranzasModel.FK_usuarios_personas", "personas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbControlCobranzasModel", "FK_usuarios_rolUsuario", "rolUsuario")]
        public rolUsuario rolUsuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<rolUsuario>("dbControlCobranzasModel.FK_usuarios_rolUsuario", "rolUsuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<rolUsuario>("dbControlCobranzasModel.FK_usuarios_rolUsuario", "rolUsuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<rolUsuario> rolUsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<rolUsuario>("dbControlCobranzasModel.FK_usuarios_rolUsuario", "rolUsuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<rolUsuario>("dbControlCobranzasModel.FK_usuarios_rolUsuario", "rolUsuario", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
